spring.application.name=animal-shelter
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/animal_shelter}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/001-init.sql

telegram.bot.enabled=${TELEGRAM_BOT_ENABLED:false}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
