--liquibase formatted sql

--changeset sapphirov:01
CREATE TABLE shelters (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(160) NOT NULL,
                          address VARCHAR(300) NOT NULL
);

CREATE TABLE animals (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(120) NOT NULL,
                         species VARCHAR(20) NOT NULL,
                         available BOOLEAN NOT NULL,
                         shelter_id BIGINT REFERENCES shelters(id)
);

CREATE TABLE adopters (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          telegram_id BIGINT NOT NULL UNIQUE,
                          username VARCHAR(255)
);

CREATE TABLE adoptions (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           adopter_id BIGINT NOT NULL REFERENCES adopters(id),
                           animal_id BIGINT NOT NULL REFERENCES animals(id),
                           status VARCHAR(30) NOT NULL,
                           started_at TIMESTAMP NOT NULL,
                           ends_at TIMESTAMP NOT NULL
);

CREATE TABLE reports (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         adoption_id BIGINT NOT NULL REFERENCES adoptions(id),
                         description VARCHAR(2000),
                         photo_file_id VARCHAR(300),
                         created_at TIMESTAMP NOT NULL,
                         status VARCHAR(30) NOT NULL
);

CREATE INDEX idx_animals_species ON animals(species);
CREATE INDEX idx_adoptions_adopter ON adoptions(adopter_id);
CREATE INDEX idx_reports_adoption ON reports(adoption_id);

--rollback DROP TABLE reports; DROP TABLE adoptions; DROP TABLE adopters; DROP TABLE animals; DROP TABLE shelters;
