--liquibase formatted sql

--changeset sapphirov:02
ALTER TABLE reports ADD COLUMN report_day DATE;
UPDATE reports SET report_day = CAST(created_at AS DATE);
ALTER TABLE reports ALTER COLUMN report_day SET NOT NULL;
ALTER TABLE reports ADD CONSTRAINT uq_reports_adoption_day UNIQUE (adoption_id, report_day);
ALTER TABLE adoptions ADD COLUMN last_escalation_on DATE;

CREATE TABLE report_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adoption_id BIGINT NOT NULL UNIQUE REFERENCES adoptions(id),
    description VARCHAR(2000),
    photo_file_id VARCHAR(300),
    updated_at TIMESTAMP NOT NULL
);

--rollback DROP TABLE report_drafts; ALTER TABLE adoptions DROP COLUMN last_escalation_on; ALTER TABLE reports DROP CONSTRAINT uq_reports_adoption_day; ALTER TABLE reports DROP COLUMN report_day;
